sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications: false
node_js:
  - 6
before_install:
  - npm install -g npm@^2
before_script:
  - npm prune
script:
  - npm run test:single